services:
  migrate:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    command: ["/app/migrate", "up"]
    environment:
      APP_NAME: insider-one-case
      APP_ENV: development
      CLICKHOUSE_ADDR: clickhouse:9000
      CLICKHOUSE_DATABASE: analytics
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: "devpassword"
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: "no"

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_NAME: insider-one-case
      APP_ENV: development
      HTTP_PORT: "8080"
      LOG_LEVEL: debug
      CLICKHOUSE_ADDR: clickhouse:9000
      CLICKHOUSE_DATABASE: analytics
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: "devpassword"
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      ALLOW_START_WITHOUT_INFRA: "true"
      WORKER_BATCH_SIZE: "250"
      WORKER_FLUSH_INTERVAL_MS: "250"
      INGEST_QUEUE_BUFFER_SIZE: "5000"
      INGEST_ENQUEUE_TIMEOUT_MS: "25"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "devpassword"
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user default --password devpassword --query 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  clickhouse_data:
  redis_data:
